@TodoMinimalAPI_HostAddress = https://localhost:7141

POST {{TodoMinimalAPI_HostAddress}}/todoitems
Content-Type: application/json

    {
        "name": "play workout",
        "isComplete": true
    }

###


GET {{TodoMinimalAPI_HostAddress}}/todoitems

###

GET {{TodoMinimalAPI_HostAddress}}/todoitems/1

###

GET {{TodoMinimalAPI_HostAddress}}/todoitems/complete

###

GET {{TodoMinimalAPI_HostAddress}}/todoitems/complete

###

PUT {{TodoMinimalAPI_HostAddress}}/todoitems/2
Content-Type: application/json

{
    "name": "sleep",
    "isComplete": true
}
###

GET {{TodoMinimalAPI_HostAddress}}/hello

###

GET {{TodoMinimalAPI_HostAddress}}/hello

###

POST {{TodoMinimalAPI_HostAddress}}/todoitems/

###

PUT {{TodoMinimalAPI_HostAddress}}/todoitems/{id}

###
