@TodoMinimalAPI_HostAddress = https://localhost:7141

POST {{TodoMinimalAPI_HostAddress}}/todoitems
Content-Type: application/json

    {
        "name": "play workout",
        "isComplete": true
    }

###


GET {{TodoMinimalAPI_HostAddress}}/todoitems

###

GET {{TodoMinimalAPI_HostAddress}}/todoitems/1

###

GET {{TodoMinimalAPI_HostAddress}}/todoitems/complete

###

GET {{TodoMinimalAPI_HostAddress}}/todoitems/complete

###

PUT {{TodoMinimalAPI_HostAddress}}/todoitems/2
Content-Type: application/json

{
    "name": "sleep",
    "isComplete": true
}
###

GET {{TodoMinimalAPI_HostAddress}}/hello

###

POST {{TodoMinimalAPI_HostAddress}}/todoitems/

###

PUT {{TodoMinimalAPI_HostAddress}}/todoitems/{id}

###

GET {{TodoMinimalAPI_HostAddress}}/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6ImFkbWluX3Njb3BlIiwicm9sZSI6ImFkbWluX3JvbGUiLCJuYW1lIjoiYWRtaW4iLCJleHAiOjE3NTg2MDY5Njl9.q05ir71ZZzojvu5p8kjbh17kqeoR9bh8F0VGHFlDc2k
###

@userId=3
@bookId=8
GET {{TodoMinimalAPI_HostAddress}}/users/{{userId}}/books/{{bookId}}

###

@username=admin 
@password=123456
POST {{TodoMinimalAPI_HostAddress}}/login?username={{username}}&password={{password}}

###
