print("============================================")
print("Input, concat and print!")
print("============================================")
name = input("Enter your name: ")
age = int(input("Enter your age: "))
print("Hello " + name + "! You are " + str(age) + " years old!")
print("Hello ", name, "! You are ", age, " years old!", sep="")
print(f"Hello {name}! You are {age} years old!")
print("10 nam sau tuoi ban se la:" + str(age + 10))